// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for macos - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyDWXLVfbNkFmWRqIhfXHi108RcIB1WC2Os',
    appId: '1:323070608349:web:f3f5b2e788286ee891ac34',
    messagingSenderId: '323070608349',
    projectId: 'hesably',
    authDomain: 'hesably.firebaseapp.com',
    storageBucket: 'hesably.firebasestorage.app',
    measurementId: 'G-BEDLBLZ2DQ',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyCSU6W03BTneZfD4R0J6ype8Zcgh8U8LhU',
    appId: '1:323070608349:android:0f1f05fded41a65c91ac34',
    messagingSenderId: '323070608349',
    projectId: 'hesably',
    storageBucket: 'hesably.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyDNXmcL5U-PzRvdO1O_rlBe2Ksvb69Lkj4',
    appId: '1:323070608349:ios:f00413913846ebf891ac34',
    messagingSenderId: '323070608349',
    projectId: 'hesably',
    storageBucket: 'hesably.firebasestorage.app',
    iosBundleId: 'com.hesably.hesablyMobile',
  );
}
